name: build

on: [push, pull_request]

env:
  DGLBACKEND: mxnet

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Analyse the code with pylint
      run: |
        pylint yamlchem
    - name: Test with pytest
      run: |
        pytest